version: "2"

services:
  redis:
    image: quay.io/sclorg/redis-6-c9s
    container_name: redis
    ports:
      - 6379:6379
    user: "1024"

  postgres:
    container_name: postgres
    image: quay.io/sclorg/postgresql-15-c9s
    environment:
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_DATABASE: packit
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 4GB
        reservations:
          memory: 2G

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: files/docker/Dockerfile.worker
      args:
        SOURCE_BRANCH: main
    image: quay.io/packit/packit-worker:dev
    command: /usr/bin/run_worker_simplified.sh
    depends_on:
      - redis
      - postgres
    environment:
      DEPLOYMENT: dev
      REDIS_SERVICE_HOST: redis
      APP: packit_service.worker.tasks
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_HOST: postgres
      POSTGRESQL_DATABASE: packit
      CELERY_RETRY_LIMIT: 0
      #SQLALCHEMY_ECHO: 1
    volumes:
      - ./packit_service:/usr/local/lib/python3.13/site-packages/packit_service:ro,z
      - ./secrets/packit/dev/packit-service.yaml:/home/packit/.config/packit-service.yaml:ro,z
    user: "1024"

  service:
    container_name: service
    build:
      context: .
      dockerfile: files/docker/Dockerfile
      args:
        SOURCE_BRANCH: main
    image: quay.io/packit/packit-service:dev
    command: bash -c "alembic-3 upgrade head && cd /usr/share/packit && python3 -m packit_service.service.app"
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    environment:
      DEPLOYMENT: dev
      REDIS_SERVICE_HOST: redis
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_HOST: postgres
      POSTGRESQL_DATABASE: packit
      HTTP_PORT: 8080
      #SQLALCHEMY_ECHO: 1
    volumes:
      - ./packit_service:/src/packit_service:ro,z
      - ./alembic:/src/alembic:rw,z
      - ./secrets/packit/dev/packit-service.yaml:/home/packit/.config/packit-service.yaml:ro,z
    user: "1024"

  beat:
    container_name: beat
    build:
      context: .
      dockerfile: files/docker/Dockerfile.worker
      args:
        SOURCE_BRANCH: main
    image: quay.io/packit/packit-worker:dev
    command: /usr/bin/run_worker_simplified.sh
    depends_on:
      - redis
      - postgres
    environment:
      CELERY_COMMAND: beat
      DEPLOYMENT: dev
      REDIS_SERVICE_HOST: redis
      APP: packit_service.worker.tasks
      POSTGRESQL_USER: packit
      POSTGRESQL_PASSWORD: secret-password
      POSTGRESQL_HOST: postgres
      POSTGRESQL_DATABASE: packit
      CELERY_RETRY_LIMIT: 0
    volumes:
      - ./packit_service:/usr/local/lib/python3.13/site-packages/packit_service:ro,z
      - ./secrets/packit/dev/packit-service.yaml:/home/packit/.config/packit-service.yaml:ro,z
    user: "1024"

  adminer:
    image: docker.io/adminer
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - 8082:8080
    user: "1024" 