# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

- name: Copy packit.wsgi file
  ansible.builtin.copy:
    src: packit.wsgi
    dest: /usr/share/packit/packit.wsgi
    mode: 0664
- name: Copy run_httpd_simplified.sh
  ansible.builtin.copy:
    src: run_httpd_simplified.sh
    dest: /usr/bin/run_httpd_simplified.sh
    mode: 0775
